name: ai_gameshow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  riverpod_generator: ^2.3.11
  riverpod_annotation: ^2.3.4
  flutter_markdown: ^0.6.19
  google_generative_ai: ^0.2.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
